name: 'Droidperf Audit'
description: 'Performance guard for Gradle'
branding:
  icon: 'zap'
  color: 'purple'
runs:
  using: 'composite'
  steps:
    - name: Run Droidperf Audit
      shell: bash
      run: npx droidperf audit . --ci
